var appUserContoller = require("../controller/AppUserContoller");
var storeController = require("../controller/StoreController");
var categoryController = require("../controller/CategoryController");
var uploadController = require("../controller/UploadController");
var feedbackController = require("../controller/FeedbackController");
var appContactUsController = require("../controller/AppContactUsController");
var rewardPointController = require("../controller/RewardPointController");
var storeReviewController = require("../controller/StoreReviewController");
var productController = require("../controller/ProductController");
var serviceController = require("../controller/ServiceController");
var favoriteController = require("../controller/FavoriteController");
var cartController = require("../controller/CartController");
var deliveryAddressController = require("../controller/DeliveryAddressController");
var promocodeController = require("../controller/PromocodeController");
var orderController = require("../controller/OrderController");
var contactUsController = require("../controller/ContactUsController");
var notificationController = require("../controller/NotificationController");
var rewardPointHistoryController = require("../controller/RewardPointHistoryController");
var bargainRequestController = require("../controller/BargainRequestController");
var reverseAuctionController = require("../controller/ReverseAuctionController");
var deliveryPartnerController = require("../controller/DeliveryPartnerController");
var pushSubscriptionController = require("../controller/PushSubscriptionController");
var productItemReviewController = require("../controller/ProductItemReviewController");
var scratchCardController = require("../controller/ScratchCardController");
var referralRewardOfferTypeRulesController = require("../controller/ReferralRewardOfferTypeRulesController");
var referralRewardOfferController = require("../controller/ReferralRewardOfferController");
var referralRewardOffersForStoreController = require("../controller/ReferralRewardOffersForStoreController");
var razorPayController = require("../controller/RazorPayController");
var statusController = require("../controller/StatusController");
var freshChatController = require("../controller/FreshChatController");
var fcmController = require("../controller/FCMController");
var iciciController = require("../controller/ICICIController");
var iciciProxyController = require("../controller/ICICIProxyController");
var iciciFTProxyController = require("../controller/ICICIFTProxyController");

var paymentLinkController = require("../controller/PaymentLinkController");
var storeJobPostingController = require("../controller/StoreJobPostingController");
var appliedJobController = require("../controller/AppliedJobController");
var couponControlller = require("../controller/CouponControlller");
var announcementControlller = require("../controller/AnnouncementControlller");


var indexRoute = require("../controller/index");

module.exports = function (app) {
    indexRoute.install(app);
    appUserContoller.install(app);
    uploadController.install(app);
    storeController.install(app);
    categoryController.install(app);
    feedbackController.install(app);
    appContactUsController.install(app);
    rewardPointController.install(app);
    storeReviewController.install(app);
    productController.install(app);
    serviceController.install(app);
    favoriteController.install(app);
    deliveryAddressController.install(app);
    promocodeController.install(app);
    orderController.install(app);
    cartController.install(app);
    contactUsController.install(app);
    notificationController.install(app);
    rewardPointHistoryController.install(app);
    bargainRequestController.install(app);
    reverseAuctionController.install(app);
    deliveryPartnerController.install(app);
    pushSubscriptionController.install(app);
    productItemReviewController.install(app);
    scratchCardController.install(app);
    referralRewardOfferTypeRulesController.install(app);
    referralRewardOfferController.install(app);
    referralRewardOffersForStoreController.install(app);
    razorPayController.install(app);
    statusController.install(app);
    freshChatController.install(app);
    fcmController.install(app);
    iciciController.install(app);
    iciciProxyController.install(app);
    iciciFTProxyController.install(app);
    paymentLinkController.install(app);
    storeJobPostingController.install(app);
    appliedJobController.install(app);
    couponControlller.install(app);
    announcementControlller.install(app);
}
